language: python

sudo: false

cache:
  directories:
    - ~/.cache/pip

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

addons:
  apt:
    packages:
    - libgdal1h
    - gdal-bin
    - libgdal-dev
    - libspatialindex-dev
    - libspatialindex1

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

env:
  - PANDAS_VERSION=v0.15.2
  - PANDAS_VERSION=v0.16.2
  - PANDAS_VERSION=master

before_install:
  - pip install -U pip
  - pip install wheel

install:
  - pip wheel -r requirements.txt
  - pip wheel -r requirements.test.txt
  - pip wheel numpy
  - pip install numpy
  - pip install -r requirements.txt
  - pip install -r requirements.test.txt
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install -r .requirements-2.6.txt; fi
  - git clone git://github.com/pydata/pandas.git
  - cd pandas
  - git checkout $PANDAS_VERSION
  - pip wheel -e .
  - pip install -e .
  - cd ..

script:
  - py.test tests --cov geopandas -v --cov-report term-missing

after_success:
  - coveralls
